apiVersion: apps/v1
kind: Deployment
metadata:
  name: computer-store
spec:
  replicas: 4
  selector:
    matchLabels:
      app: computer-store
  template:
    metadata:
      labels:
        app: computer-store
    spec:
      containers:
      - name: computer-store
        image: vikas0112/computer-store:20260406-164448
        ports:
        - containerPort: 3000
