apiVersion: apps/v1
kind: Deployment
metadata:
  name: computer-store
spec:
  replicas: 2
  selector:
    matchLabels:
      app: computer-store
  template:
    metadata:
      labels:
        app: computer-store
    spec:
      containers:
      - name: computer-store
        image: computer-store:latest
        ports:
        - containerPort: 3000
